---
title: "about"
subtitle: "Professional bio"
title-block-banner: true
---

Dr. Ludovic DE CUYPERE currently holds the positions of Associate Professor of English Linguistics at Vrije Universiteit Brussel and of Research Support Officer at the Linguistics Department of Ghent University. He completed his MA in Germanic Languages and Literature from UGent in 2001, followed by a PhD in Germanic Languages and Literature from the same university in 2007.

His doctoral dissertation, published in 2008 as *Limiting the Iconic* with John Benjamins, involved an epistemological investigation of iconicity in language. He served as a postdoctoral fellow with the Research Foundation Flanders (FWO) from 2007 until 2013, working on a corpus-based investigation of the history of the English dative alternation.

His research has focused on alternating syntactic constructions, which he has studied from multiple perspectives and in various languages. He has contributed to theoretical and epistemological aspects of linguistic debate, such as the application of evolutionary theory concepts to language change (exaptation), the conceptual nature of (prepositional) semantics, iconicity as a functional explanation, and the grammatical status of alternating syntactic constructions. He has further contributed to the methodological design and statistical analysis of multiple studies. 
An advocate of Open Science, he has published various datasets on TROLLing, a curated repository under DataverseNo.

## Positions



## Degrees

- 2003 -- 2007: Phd in Languages and Literary studies: Germanic Languages (Ghent University). 

> PhD Dissertation: Limiting the iconic: from the metatheoretical foundations to the creative possibilities of iconicity in language.   

- 2001 -- 2003: Teacher training accredition
- 1999 -- 2001: Master of arts (licentiaat) in Germanic Languages (Ghent University)
- 1996 -- 1999: Bachelor of arts (kandidaat) in Germanic Languages (Ghent University)

## Organisation

I’ve organized multiple scientific conferences, but I am most proud of being the co-organizer (alongside Koen Plevoets) of the annual summer school, Methods in Language Sciences (MILS), held at Ghent University each July. We have hosted this summer school since 2020, and in recent years, we have welcomed over a hundred participants from around the globe. In 2025, we hosted 114 participants from 42 universities across 19 countries. We are currently preparing for MILS 2026 and have an excellent lineup of courses already confirmed. More details will be available soon at [MILS2026](https://www.mils.ugent.be/).



